
import { GraduationCap, BookOpen, Award, Code2, Palette, Brain, Wrench, Users, Code, Heart,Apple, RotateCcw, PartyPopper, Cloud, Trophy, Medal, Smartphone } from 'lucide-react';

export const Information: any = {
    educationDetails: [{
      id: 1,
      level: "Bachelor's Degree",
      institution: "Indira Gandhi Delhi Technical University for Women",
      degree: "Btech - Computer Science with AI",
      duration: "2023 - Present",
      location: "New Delhi, Delhi",
      grade: "CGPA: 9.63/10 (Upto 4th Semester)",
      icon: GraduationCap,
      color: "from-blue-500 to-purple-600"
    },
    {
      id: 2,
      level: "Higher Secondary (12th)",
      institution: "BLS International School",
      degree: "CBSE Board",
      duration: "2022",
      location: "Hathras, Uttar Pradesh",
      grade: "Percentage: 98.8%",
      icon: BookOpen,
      color: "from-green-500 to-teal-600"
    },
    {
      id: 3,
      level: "Secondary (10th)",
      institution: "BLS International School",
      degree: "CBSE Board",
      duration: "2020",
      location: "Hathras, Uttar Pradesh",
      grade: "Percentage: 96.2%",
      icon: Award,
      color: "from-orange-500 to-red-600"
    }],
    skills:[
    {
      category: "Programming Languages",
      icon: Code2,
      color: "from-blue-500 to-cyan-500",
      skills: [
        { name: "Java", level: 90 },
        { name: "Python", level: 70 },
        { name: "Dart", level: 50 },
      ],
    },
    {
      category: "Development",
      icon: Palette,
      color: "from-purple-500 to-pink-500",
      skills: [
        { name: "HTML", level: 90 },
        { name: "CSS", level: 80 },
        { name: "JavaScript", level: 90 },
        { name: "Flutter", level: 50 },
        { name: "Next.js", level: 80 },
      ],
    },
    {
      category: "AI/ML",
      icon: Brain,
      color: "from-green-500 to-emerald-500",
      skills: [
        { name: "Machine Learning", level: 60 },
        { name: "Deep Learning", level: 50 },
        { name: "Computer Vision", level: 50 },
      ],
    },
    {
      category: "Developer Tools",
      icon: Wrench,
      color: "from-orange-500 to-red-500",
      skills: [
        { name: "GitHub", level: 90 },
        { name: "VS Code", level: 95 },
        { name: "IntelliJ", level: 90 },
        { name: "Google Colab", level: 70 },
        { name: "Snowflake", level: 70 },
        { name: "Postgres", level: 70 },
      ],
    },
    {
      category: "Relevant Courses",
      icon: BookOpen,
      color: "from-indigo-500 to-purple-500",
      skills: [
        { name: "DSA", level: 80 },
        { name: "DBMS", level: 70 },
        { name: "Data Science", level: 60 },
        { name: "OOPS", level: 90 },
        { name: "Computer Networks", level: 70 },
        { name: "Operating System", level: 80 },
        { name: "SQL", level: 80 },
      ],
    },
    {
      category: "Soft Skills",
      icon: Users,
      color: "from-teal-500 to-blue-500",
      skills: [
        { name: "Time Management", level: 90 },
        { name: "Teamwork", level: 90 },
        { name: "Positive Attitude", level: 80 },
        { name: "Problem Solving", level: 80 },
      ],
    },
  ],
  experiences: [
    {
      id: 1,
      role: "Software Development Intern",
      company: "Motorq",
      location: "Bangalore, India",
      duration: "May 2025 – July 2025",
      type: "NEST Internship",
      description: "Completed a two-month internship working on real-world projects",
      achievements: [
        "Developed an interactive cost analysis dashboard enabling the internal team to investigate monthly cost variations and gain insights within seconds, reducing analysis time from hours to seconds",
        "Enhanced backend processes by fixing Snowflake sync issues, migrating data fetching from PostgreSQL to Snowflake",
        "Integrated current month data from Excel files and implemented anomaly detection alerts",
        "Researched cost-monitoring tools like Kubecost and OpenCost, gaining foundational knowledge of Kubernetes",
      ],
      technologies: ["Snowflake", "PostgreSQL","Next.js", "SQL", "Kubernetes", "Docker", "Git"],
      certificate: "https://drive.google.com/file/d/1SfnfK8a42ReP8XyWrmAN4vEIZ19nrCy4/view",
      icon: Code,
      color: "from-blue-500 to-purple-600",
      bgPattern: "bg-gradient-to-br from-blue-500/10 to-purple-600/10",
    },
    {
      id: 2,
      role: "Computer Vision and Deep Learning Intern",
      company: "Centre Of Excellence - Artificial Intelligence, IGDTUW",
      location: "Delhi, India",
      duration: "June 2024 – August 2024",
      type: "Training",
      description: "Completed an 8-week training program exploring concepts of computer vision and deep learning",
      achievements: [
        "Gained comprehensive understanding of computer vision fundamentals and deep learning architectures",
        "Worked on a hands-on project titled 'Rotten Fruit Detection' using advanced image processing techniques",
        "Implemented machine learning models for real-time fruit quality assessment",
        "Developed expertise in image classification and object detection algorithms",
      ],
      technologies: [
        "Computer Vision",
        "Deep Learning",
        "Python",
        "TensorFlow",
        "Image Processing",
        "Machine Learning",
      ],
      certificate: "https://drive.google.com/file/d/1ZiGc7dpUQ99darA1SfnUhq4hMfOzVYYM/view",
      icon: Brain,
      color: "from-green-500 to-teal-600",
      bgPattern: "bg-gradient-to-br from-green-500/10 to-teal-600/10",
    },
  ],
  projects: [
    {
      id: 1,
      title: "Mood Based Workout Recommendation",
      subtitle: "AI-Powered Fitness Assistant",
      description:
        "Developed an AI-powered web application that recommends personalized workouts based on users' emotional state and fitness preferences.",
      longDescription:
        "An innovative web application that combines artificial intelligence with fitness to provide personalized workout recommendations. The system analyzes user inputs including emotional state, fitness level, and preferences to suggest tailored physical or mental relaxation exercises.",
      date: "October 2024",
      technologies: ["HTML", "CSS", "JavaScript", "Flask", "MySQL", "Machine Learning", "AI"],
      features: [
        "AI-powered recommendation engine",
        "Emotional state analysis",
        "Personalized workout suggestions",
        "User-centered design interface",
        "Physical and mental exercise options",
        "Collaborative development approach",
      ],
      achievements: [
        "Implemented machine learning model for personalized recommendations",
        "Demonstrated strong skills in user-centered design and AI integration",
        "Successfully deployed live web application",
        "Showcased collaborative teamwork skills",
      ],
      liveUrl: "https://mood-based-workout-reccomendation.vercel.app",
      githubUrl: "https://github.com/kopalg20/MoodBasedWorkoutReccomendation",
      icon: Heart,
      color: "from-pink-500 to-red-500",
      bgGradient: "from-pink-500/10 to-red-500/10",
      category: "Web Development",
      status: "Live",
    },
    {
      id: 2,
      title: "Rotten Fruit Detection",
      subtitle: "Computer Vision for Agriculture",
      description:
        "Developed a deep learning model using Convolutional Neural Networks (CNNs) designed to reduce waste and ensure quality in agriculture and retail.",
      longDescription:
        "A sophisticated computer vision system that leverages deep learning to identify and classify rotten fruits. This project addresses real-world challenges in agriculture and retail by providing automated quality assessment tools.",
      date: "August 2024",
      technologies: ["Python", "TensorFlow", "CNNs", "Computer Vision", "Deep Learning", "Image Processing"],
      features: [
        "Convolutional Neural Network architecture",
        "Real-time fruit quality assessment",
        "High accuracy classification system",
        "Scalable for agricultural applications",
        "Automated waste reduction solution",
        "Quality assurance for retail",
      ],
      achievements: [
        "Successfully implemented CNN-based detection system",
        "Achieved high accuracy in fruit quality classification",
        "Designed solution for real-world agricultural challenges",
        "Contributed to waste reduction and quality assurance",
      ],
      liveUrl: null,
      githubUrl: "https://colab.research.google.com/drive/14VUF2siKAyPh6b6HHRnFeRqAY6sI-w1O?usp=chrome_ntp",
      icon: Apple,
      color: "from-green-500 to-emerald-500",
      bgGradient: "from-green-500/10 to-emerald-500/10",
      category: "Machine Learning",
      status: "Completed",
    },
  ],
  roles: [
    {
      id: 1,
      position: "Interact Relation Chair",
      organization: "Rotaract Club IGDTUW",
      duration: "June 2025 – Present",
      location: "IGDTUW, Delhi",
      type: "Leadership Role",
      description:
        "Leading inter-club relations and fostering collaborative partnerships within the Rotaract community.",
      responsibilities: [
        "Coordinate inter-club activities and collaborative events",
        "Build and maintain relationships with Interact clubs",
        "Attended social service events like donation drives, NGO visits and many more",
        "Coordinate with artist for fun events",
        "Formulate ideas for new events and activities",
      ],
      skills: ["Leadership", "Relationship Building", "Event Coordination", "Strategic Planning", "Communication"],
      icon: RotateCcw,
      color: "from-blue-500 to-indigo-600",
      bgGradient: "from-blue-500/10 to-indigo-600/10",
      status: "Current",
    },
    {
      id: 2,
      position: "HR Head Coordinator",
      organization: "Taarangana",
      duration: "September 2024 – Present",
      location: "IGDTUW, Delhi",
      type: "Coordination Role",
      description: "Managing human resources and team coordination for one of the largest cultural festivals.",
      responsibilities: [
        "Lead recruitment and selection processes for fest teams",
        "Coordinate among teams to ensure smooth operations",
        "Manage event logistics",
        "In direct coordination with the fest judges and artists",
        "Handle conflict resolution and team motivation initiatives",
      ],
      skills: ["Human Resources", "Team Management", "Event Planning", "Conflict Resolution", "Training & Development"],
      icon: PartyPopper,
      color: "from-purple-500 to-pink-600",
      bgGradient: "from-purple-500/10 to-pink-600/10",
      status: "Current",
    },
    {
      id: 3,
      position: "Associate of Public Relations (PR) Team",
      organization: "AWS Cloud Club IGDTUW",
      duration: "August 2024 – Present",
      location: "IGDTUW, Delhi",
      type: "Technical Role",
      description: "Promoting cloud computing awareness and managing external communications for the AWS Cloud Club.",
      responsibilities: [
        "Develop and execute PR strategies for club events and initiatives",
        "Ensure maximum outreach and engagement for club activities",
        "Manage club's online presence and brand reputation",
      ],
      skills: [
        "Public Relations",
        "Content Creation",
        "Social Media Management",
        "AWS Technologies",
        "Brand Management",
      ],
      icon: Cloud,
      color: "from-orange-500 to-red-600",
      bgGradient: "from-orange-500/10 to-red-600/10",
      status: "Current",
    },
  ],
  achievements: [
    {
      id: 1,
      title: "CBSE Academic Excellence Award",
      subtitle: "Second District Topper in Senior Secondary Examinations",
      description:
        "Recognized for outstanding academic performance in CBSE senior secondary examinations, achieving second position in the district.",
      date: "2020",
      organization: "Central Board of Secondary Education (CBSE)",
      details: [
        "Achieved second position in district-wide senior secondary examinations",
        "Demonstrated exceptional performance across all subjects",
        "Maintained consistent academic excellence throughout senior secondary",
        "Recognized for dedication and hard work in studies",
      ],
      icon: Trophy,
      color: "from-yellow-500 to-orange-500",
      bgGradient: "from-yellow-500/10 to-orange-500/10",
    },
    {
      id: 2,
      title: "Outstanding Achiever Award",
      subtitle: "Recognition by Amar Ujala",
      description:
        "Honored by Amar Ujala newspaper for being the second district topper in senior secondary examinations.",
      date: "2020",
      organization: "Amar Ujala",
      details: [
        "Featured in Amar Ujala newspaper for academic achievement",
        "Recognized as second district topper in senior secondary",
        "Public acknowledgment of educational excellence",
        "Inspiring example for other students in the community",
      ],
      icon: Medal,
      color: "from-purple-500 to-indigo-600",
      bgGradient: "from-purple-500/10 to-indigo-600/10",
    },
    {
      id: 3,
      title: "Certified Mentee - Mobile Development Course",
      subtitle: "Google Developer Student Clubs (GDSC) IGDTUW",
      description: "Successfully completed comprehensive mobile development training program under GDSC mentorship.",
      date: "2024",
      organization: "Google Developer Student Clubs (GDSC) IGDTUW",
      details: [
        "Completed structured mobile development curriculum",
        "Gained hands-on experience in mobile app development",
        "Participated in coding workshops and technical sessions",
        "Developed practical mobile applications during the course",
      ],
      icon: Smartphone,
      color: "from-green-500 to-teal-600",
      bgGradient: "from-green-500/10 to-teal-600/10",
      certificateUrl: "https://drive.google.com/file/d/1VYBO9zcuNIT-hKVnNoK56nAkRF0rd4eE/view", // Replace with actual certificate URL
    },
    {
      id: 4,
      title: "Java Programming Course Completion",
      subtitle: "Comprehensive Java Development Training",
      description:
        "Successfully completed an extensive Java programming course on Udemy, mastering core Java concepts and advanced programming techniques.",
      date: "2024",
      organization: "Udemy",
      details: [
        "Mastered core Java programming concepts and syntax",
        "Learned object-oriented programming principles",
        "Developed practical Java applications and projects",
        "Gained expertise in Java development best practices",
      ],
      icon: Code,
      color: "from-blue-500 to-cyan-500",
      bgGradient: "from-blue-500/10 to-cyan-500/10",
    },
  ]
}